$('.owl-carousel').owlCarousel({
    loop:true,
    margin:15,
    nav:false,
    responsive:{
        0:{
            items:1
        },
        400:{
            items:2
        },
        600:{
            items:3
        },
        850:{
            items:4
        },
        1050:{
            items:5
        },
        1400:{
            items:6
        },
    }
})